### ISSUE TITLE
Runing Banduppy occurs an error

### ISSUE THREAD

**Issue by gswylq** [band-unfolding/banduppy#6]
Dear Banduppy team,

When I am calculatting the unfolding band of MoS2 using Abinit 9.4.1 and Banduppy. The k-path.py and the WF file are obtained. However, when I run the banduppy script (k-path-suan.py), an error occur.

 The WF file is very big, so the error output file and abinit input files are only attached in email.

If you have the time, could you please help me to give some suggestions.

 Look forward to hearing from you

Yours Sincerely,

Qiang Li   

[bandupp_mos2.zip](https://github.com/band-unfolding/banduppy/files/6475808/bandupp_mos2.zip)

**Comment by stepan-tsirkin** [comment]
dear @gswylq  

does the error happen for this particular caclulation, or for any calculation with Abinit?

Say, if you just do a calculation for a small system (whatever smalles you may think of), and try to read it with 

```
bands=banduppy.BandStructure(fWFK='t42o_DS2_WFK',code="abinit")
```

Will the same error occur on your version of Abinit? If yes, you may send your WFK file (which should be small in that case)

**Comment by gswylq** [comment]
Dear @stepan-tsirkin 
I calculate  a small graphene using banduppy and abinit.  Ther results are obtained and an error occurs. The WFK  and input files are upload. 
 
Please help me. Thank you. 

[k-path-suan.py.txt](https://github.com/band-unfolding/banduppy/files/6485215/k-path-suan.py.txt)
[t42.in.txt](https://github.com/band-unfolding/banduppy/files/6485216/t42.in.txt)
[t42o_DS2_WFK.txt](https://github.com/band-unfolding/banduppy/files/6485217/t42o_DS2_WFK.txt)

**Comment by stepan-tsirkin** [comment]
dear @gswylq 

could you try to install irrep from the following [branch](https://github.com/stepan-tsirkin/irrep/tree/fix_abinit)

and run a script 

```
import irrep
from irrep import bandstructure
print (irrep.__version__)
bandstructure.BandStructure(code="abinit", fWFK="t42o_DS2_WFK")
```
It will go a bit further, giving an eerror:

```
1.5.6a
using fortio to read
codsvn='9.4.1   ', headform=80, fform=2 
WARNING, the version 9.4.1    of abinit is not 8.6.3 
ecut=680.28465 eV
/home/stepan/arbeit/banduppy-error/testing_env/lib/python3.8/site-packages/fortio.py:297: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  dtype = np.dtype(dtype).newbyteorder(self.byteorder)
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    bandstructure.BandStructure(code="abinit", fWFK="t42o_DS2_WFK")
  File "/home/stepan/arbeit/banduppy-error/irrep/bandstructure.py", line 60, in __init__
    self.__init_abinit(
  File "/home/stepan/arbeit/banduppy-error/irrep/bandstructure.py", line 179, in __init_abinit
    header = AbinitHeader(WFKname)
  File "/home/stepan/arbeit/banduppy-error/irrep/__readfiles.py", line 122, in __init__
    raise ValueError(
ValueError: istwfk should be 1 for all kpoints. found [2 1 1 1 1 1 1]
```
But this is expected. You should specify `istwfk=1` for all kpoints in the abinit input to make it work with irrep or banduppy. Please redo your calculation with `istwfk=1`  and run the script again. 
Please tell me if the calculation proceeds to the end, or any other error arises.

**Comment by gswylq** [comment]
Dear @stepan-tsirkin 

I use a command(pip install -e .) to instal fix-abinit irrep files , and the errors are as follow:

(python37_abinit) gswylq@gswylq-Super-Server:~/qe_soft/irrep$ python 
Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import irrep
>>> from irrep import bandstructure
>>> print (irrep.__version__)
1.5.6
>>> bandstructure.BandStructure(code="abinit", fWFK="t42o_DS2_WFK")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gswylq/qe_soft/irrep/irrep/bandstructure.py", line 129, in __init__
    fWFK, Ecut, IBstart, IBend, kplist, EF=EF, onlysym=onlysym
  File "/home/gswylq/qe_soft/irrep/irrep/bandstructure.py", line 291, in __init_abinit
    header = AbinitHeader(WFKname)
  File "/home/gswylq/qe_soft/irrep/irrep/readfiles.py", line 120, in __init__
    record = fWFK.read_record('a6,2i4')
  File "/home/gswylq/miniconda3/envs/python37_abinit/lib/python3.7/site-packages/scipy/io/_fortran.py", line 260, in read_record
    'dtypes given ({1}).'.format(first_size, block_size))
ValueError: Size obtained (16) is not a multiple of the dtypes given (14).

The installation process may not be correct.

**Comment by stepan-tsirkin** [comment]
I see, could you also attach the new WFK file.
